services:
  - type: web
    name: fjc-pizza-app
    runtime: python
    runtimeVersion: "3.11"
    buildCommand: |
      pip install -r requirements.txt
      python sales_inventory_system/manage.py migrate
      python sales_inventory_system/manage.py collectstatic --no-input
    startCommand: |
      gunicorn sales_inventory_system.sales_inventory.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: fjc-pizza-db
          property: connectionString
      - key: PYTHONUNBUFFERED
        value: "1"
    autoDeploy: true
    healthCheckPath: /admin/
    previewPlan: free

  - type: postgresql
    name: fjc-pizza-db
    ipAllowList: []
    plan: free
    postgresSQLVersion: "15"
